/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{vue,ts,js}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#404752',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        outline: '#717783',
        'outline-variant': '#c0c7d4',
        'surface-tint': '#0060ab',
        primary: '#005faa',
        'on-primary': '#ffffff',
        'primary-container': '#0078d4',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#a3c9ff',
        secondary: '#006687',
        'on-secondary': '#ffffff',
        'secondary-container': '#60cdff',
        'on-secondary-container': '#005572',
        tertiary: '#5e5d5d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#777676',
        'on-tertiary-container': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d3e3ff',
        'primary-fixed-dim': '#a3c9ff',
        'on-primary-fixed': '#001c39',
        'on-primary-fixed-variant': '#004883',
        'secondary-fixed': '#c1e8ff',
        'secondary-fixed-dim': '#74d1ff',
        'on-secondary-fixed': '#001e2b',
        'on-secondary-fixed-variant': '#004d67',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1b1c1c',
        'on-tertiary-fixed-variant': '#474746',
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        'surface-variant': '#e2e2e2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '24px',
        unit: '8px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '16px',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'PingFang SC',
          'Hiragino Sans GB',
          'Microsoft YaHei',
          'Helvetica Neue',
          'Helvetica',
          'Arial',
          'sans-serif'
        ],
      },
      fontSize: {
        'display-lg': ['42px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'caption-xs': ['11px', { lineHeight: '14px', fontWeight: '400' }],
      },
      backdropBlur: {
        acrylic: '32px',
      },
      transitionTimingFunction: {
        'fluent': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
}
